name: NPM Publish Workflow

on:
  release:
    types: [created]
  workflow_dispatch:
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup git
        run: |
          git config --global user.email "jordansimsmith@gmail.com"
          git config --global user.name "Jordan Sim-Smith"

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn install

      - name: Bump version
        run: npm version patch -m "[CI] Bump package version"

      - name: Publish package
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Push version bump
        run: git push https://${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

